/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeCardRouteImport } from './routes/welcome-card'
import { Route as PreMatchRouteImport } from './routes/pre-match'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeCardRoute = WelcomeCardRouteImport.update({
  id: '/welcome-card',
  path: '/welcome-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PreMatchRoute = PreMatchRouteImport.update({
  id: '/pre-match',
  path: '/pre-match',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-match': typeof PreMatchRoute
  '/welcome-card': typeof WelcomeCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-match': typeof PreMatchRoute
  '/welcome-card': typeof WelcomeCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-match': typeof PreMatchRoute
  '/welcome-card': typeof WelcomeCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding' | '/pre-match' | '/welcome-card'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/pre-match' | '/welcome-card'
  id: '__root__' | '/' | '/onboarding' | '/pre-match' | '/welcome-card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  PreMatchRoute: typeof PreMatchRoute
  WelcomeCardRoute: typeof WelcomeCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-card': {
      id: '/welcome-card'
      path: '/welcome-card'
      fullPath: '/welcome-card'
      preLoaderRoute: typeof WelcomeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-match': {
      id: '/pre-match'
      path: '/pre-match'
      fullPath: '/pre-match'
      preLoaderRoute: typeof PreMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  PreMatchRoute: PreMatchRoute,
  WelcomeCardRoute: WelcomeCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
