/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeCardRouteImport } from './routes/welcome-card'
import { Route as PreMatchRouteImport } from './routes/pre-match'
import { Route as PostMatchRouteImport } from './routes/post-match'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeCardRoute = WelcomeCardRouteImport.update({
  id: '/welcome-card',
  path: '/welcome-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PreMatchRoute = PreMatchRouteImport.update({
  id: '/pre-match',
  path: '/pre-match',
  getParentRoute: () => rootRouteImport,
} as any)
const PostMatchRoute = PostMatchRouteImport.update({
  id: '/post-match',
  path: '/post-match',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/post-match': typeof PostMatchRoute
  '/pre-match': typeof PreMatchRoute
  '/welcome-card': typeof WelcomeCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/post-match': typeof PostMatchRoute
  '/pre-match': typeof PreMatchRoute
  '/welcome-card': typeof WelcomeCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/post-match': typeof PostMatchRoute
  '/pre-match': typeof PreMatchRoute
  '/welcome-card': typeof WelcomeCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/match'
    | '/onboarding'
    | '/post-match'
    | '/pre-match'
    | '/welcome-card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/match'
    | '/onboarding'
    | '/post-match'
    | '/pre-match'
    | '/welcome-card'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/match'
    | '/onboarding'
    | '/post-match'
    | '/pre-match'
    | '/welcome-card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  MatchRoute: typeof MatchRoute
  OnboardingRoute: typeof OnboardingRoute
  PostMatchRoute: typeof PostMatchRoute
  PreMatchRoute: typeof PreMatchRoute
  WelcomeCardRoute: typeof WelcomeCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-card': {
      id: '/welcome-card'
      path: '/welcome-card'
      fullPath: '/welcome-card'
      preLoaderRoute: typeof WelcomeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-match': {
      id: '/pre-match'
      path: '/pre-match'
      fullPath: '/pre-match'
      preLoaderRoute: typeof PreMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-match': {
      id: '/post-match'
      path: '/post-match'
      fullPath: '/post-match'
      preLoaderRoute: typeof PostMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  MatchRoute: MatchRoute,
  OnboardingRoute: OnboardingRoute,
  PostMatchRoute: PostMatchRoute,
  PreMatchRoute: PreMatchRoute,
  WelcomeCardRoute: WelcomeCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
